### ISSUE TITLE
Parsing arguments in a workspace with more than one meson package

### ISSUE THREAD

**Issue by leorich** [colcon/colcon-meson#16]
Since there is just one global way to set meson options, the options given are passed to all of the meson projects in the source tree. 

Meson errors out if it gets non existent options:

`ERROR: Unknown options: "foo_option"`

This limits the number of meson projects you can have in your workspace to one (at least if you need to pass in any options).

**Comment by christianrauch** [comment]
Passing the options to all projects mirrors the behaviour of colcon-cmake.

Which meson version are you using? In version 0.60, passing unknown options turned from a warning into a fatal error (https://mesonbuild.com/Release-notes-for-0-60-0.html#unknown-options-are-now-always-fatal).

If you want to use different options for different projects, you have to create a [`colcon.meta` file](https://colcon.readthedocs.io/en/released/user/configuration.html) of the form:
```yaml
names:
  package1:
    meson-args: ["--buildtype=debug", "--auto-features=disabled", "-Dparam1=arg1", "-Dparam2=arg2"]
  package2:
    meson-args: ["--warnlevel=0", "--buildtype=release", "-Dparam1=arg1", "-Dparam2=arg2"]
```
